// src/pages/app/sidebar/Project.svelte
<script>
  import { handlePlural } from "@/util/string";
  import { Svue } from "svue";

  export let project;

  $: docs = handlePlural(project.documentCount, "Document", true);
  // Hide text for notes and collaborators if empty
  $: notes = handlePlural(project.annotationCount, "Note");
  $: collaborators = handlePlural(project.collaboratorCount, "Collaborator");

  $: infoString = [docs, notes, collaborators]
    .filter(x => x.length > 0)
    .join(", ");
</script>

<style lang="scss">
  .project {
    padding: 11px 25px;

    &:hover {
      cursor: pointer;
      background: rgba(0, 0, 0, 0.03);
      opacity: $hover-opacity;
    }
  }

  .title {
    font-size: $normal;
  }

  .sub {
    font-size: $small;
    line-height: 15px;
    color: $gray;
  }
</style>

<div class="project">
  <div class="title">{project.title}</div>
  <div v-if="ownProject" class="sub">Shared by {project.accountName}</div>
  <div class="sub">{infoString}</div>
</div>

// src/sidebar/Project.vue
<template>
  <div class="project">
    <div class="title">{{ project.title }}</div>
    <div v-if="ownProject" class="sub">
      Shared by {{ project.account_full_name }}
    </div>
    <div class="sub">{{ infoString }}</div>
  </div>
</template>

<style lang="scss" scoped>
.project {
  padding: 11px 25px;

  &:hover {
    cursor: pointer;
    background: rgba(0, 0, 0, 0.03);
    opacity: $hover-opacity;
  }
}

.title {
  font-size: $normal;
}

.sub {
  font-size: $small;
  line-height: 15px;
  color: $gray;
}
</style>

<script>
function wrapString(value, str, allowZero = false) {
  if (!allowZero && value == 0) return "";
  if (value == 1) return `1 ${str}`;
  return `${value} ${str}s`;
}

export default {
  props: {
    project: Object
  },
  computed: {
    collaboratorCount() {
      return this.project.collaborators.length;
    },
    ownProject() {
      return this.collaboratorCount > 0;
    },
    docsString() {
      return wrapString(this.project.document_count, "Document", true);
    },
    notesString() {
      return wrapString(this.project.annotation_count, "Note");
    },
    collaboratorString() {
      return wrapString(this.collaboratorCount, "Collaborator");
    },
    infoString() {
      const infoBits = [
        this.docsString,
        this.notesString,
        this.collaboratorString
      ].filter(x => x.length > 0);
      return infoBits.join(", ");
    }
  }
};
</script>
