// src/main_container/NoDocuments.vue
<template>
  <div class="container">
    <h2>Upload your first document</h2>
    <div class="img">
      <img svg-inline src="../assets/document_cartoon.svg" alt draggable="false" />
    </div>
    <div class="text">
      <p>Upload a PDF file to get started using DocumentCloud. You can drag the file into this window, or click on the blue “Upload” button above.</p>
      <p>Once you upload a file, DocumentCloud will process the document and extract its contents. It may take a few minutes for this to complete, but once it’s done your document will be optimized for analysis and sharing on the web.</p>
    </div>
  </div>
</template>

<style scoped>
.container {
  margin: 1em 1.5em;
  background: #fbf9f3;
  padding: 1em;
  border-radius: 10px;
}

h2 {
  font-size: 16px;
  font-weight: 600;
  margin: 1.5em 0;
  padding-left: 18px;
}

.img,
.text {
  display: inline-block;
  vertical-align: top;
}

.text {
  max-width: 80ch;
  width: 30vw;
  margin: 0 2em 1em 2em;
}

p {
  font-size: 15px;
  line-height: 22px;
  margin: 1 1em;
}
</style>

// src/lib/components/documents/NoDocuments.svelte
<script>
  import { _ } from "svelte-i18n";

  // SVG assets
  import { Search24 } from "svelte-octicons";
</script>

<div class="no-results">
  <h2>{$_("noDocuments.noSearchResults")}</h2>
  <div class="img">
    <Search24 height="32" width="32" />
  </div>
  <div class="text">
    <p>
      {$_("noDocuments.queryNoResults")}
    </p>
  </div>
</div>

<style>
  .no-results {
    margin: 1em 1.5em;
    background: var(--yellow-light);
    padding: 1em;
    border-radius: 10px;
  }

  h2 {
    font-size: 16px;
    font-weight: 600;
    margin: 1.5em 0;
    padding-left: 18px;
  }

  .img,
  .text {
    display: inline-block;
    vertical-align: top;
  }

  .text {
    max-width: 80ch;
    width: 30vw;
    margin: 0 2em 1em 2em;
  }
  .text :global(a) {
    color: var(--primary);
  }

  .text p {
    font-size: 15px;
    line-height: 22px;
    margin: 5px 0;
  }

  p {
    margin: 0 1em;
  }
</style>
