// src/common/dialog/ConfirmDialog.svelte
<script>
  import Button from "@/common/Button";
  import {
    confirmDialog,
    runConfirm,
    hideConfirm,
  } from "@/manager/confirmDialog";
</script>

<div>
  <div class="mcontent">
    <h1>{$confirmDialog.title}</h1>
    <p>{$confirmDialog.body}</p>
    <div class="buttonpadded">
      <Button danger={true} on:click={runConfirm}>
        {$confirmDialog.buttonText}
      </Button>
      <Button secondary={true} on:click={hideConfirm}>Cancel</Button>
    </div>
  </div>
</div>

// src/main_container/ConfirmDialog.vue
<template>
  <div>
    <div class="mcontent">
      <h1>{{ title }}</h1>
      <p>{{ body }}</p>
      <div class="buttonpadded">
        <Button :color="buttonColor" @click="confirm()">{{
          buttonText
        }}</Button>
        <Button :secondary="true" @click="dismiss()">Cancel</Button>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.buttonpadded {
  margin: 25px 0 25px -5px;

  ::v-deep button {
    margin: 0 5px;
  }
}
</style>

<script>
import Button from "@/common/Button";

export default {
  components: { Button },
  computed: {
    dialog() {
      return this.$extensions.confirmDialog;
    },
    title() {
      return this.dialog.title;
    },
    body() {
      return this.dialog.body;
    },
    buttonText() {
      return this.dialog.buttonText;
    },
    buttonColor() {
      return this.dialog.buttonColor;
    },
    confirmFn() {
      return this.dialog.confirmFn;
    }
  },
  methods: {
    confirm() {
      this.dialog.runConfirm();
    },
    dismiss() {
      this.dialog.hideConfirm();
    }
  }
};
</script>
