// src/pages/app/UploadDialog.svelte
<script>
  // Components
  import File from "./File";
  import Button from "@/common/Button";
  import DropZone from "@/common/DropZone";
  import FilePicker from "@/common/FilePicker";

  // API
  import { uploadDocuments } from "@/api/document";

  // Stores
  import { layout } from "@/manager/layout";
  import { handleNewDocument } from "@/manager/documents";

  import { onMount } from "svelte";
  import emitter from "@/emit";

  const emit = emitter({
    setDismissable() {}
  });

  export let initialFiles = [];

  let files = [];
  let id = 0;
  let uploadMode = false;
  let uploadFiles = [];
  let uploadAdditional = false;
  let errorMessage = null;

  $: displayFiles = uploadMode == false ? files : uploadFiles;

  let numUploaded;
  $: {
    // Set numUploaded
    if (!uploadMode) {
      numUploaded = 0;
    } else {
      let total = 0;
      for (let i = 0; i < uploadFiles.length; i++) {
        total += uploadFiles[i].done ? 1 : 0;
      }
      numUploaded = total;
    }
  }

  $: error = errorMessage != null;

  onMount(() => {
    handleFiles({ detail: initialFiles });
  });

  function handleFiles({ detail: newFiles }) {
    for (let i = 0; i < newFiles.length; i++) {
      files.push({
        index: id++,
        file: newFiles[i]
      });
    }
    files = files;
  }

  function removeFile(index) {
    files = files.filter(file => file.index != index);
  }

  function upload() {
    uploadFiles = files.map((file, i) => {
      return {
        file: file.file,
        progress: 0,
        done: false,
        index: i
      };
    });
    emit.setDismissable(false);
    uploadMode = true;

    uploadDocuments(
      files,
      (index, progress) => {
        // Progress handler
        uploadFiles[index].progress = progress;
      },
      async (id, index) => {
        // Complete handler
        uploadFiles[index].done = true;
        await handleNewDocument(id);
      },
      () => {
        // All complete handler
        $layout.uploading = false;
      },
      message => {
        this.errorMessage = message;
        this.$emit("setDismissable", true);
      }
    );
  }
</script>

<style lang="scss">
  .actions {
    margin: 1.5em 0;
  }

  .files {
    display: table;
    width: 100%;
  }

  .padright {
    margin-right: 12px;
  }

  .dropper {
    margin: 24px 0;
  }

  .sectionbreak {
    border-bottom: solid 1px $gray;
    margin: 2em 0 1.5em 0;
  }

  .padder {
    margin: 1.5em 0 2.5em 0;
  }

  .vpadded {
    margin: 2em 0 2.5em 0;
  }

  p.subtitle {
    color: $gray;
  }
</style>

<div>
  <div class="mcontent">
    {#if !uploadMode}
      <div>
        <h1>Document Upload</h1>
        {#if files.length == 0}
          <p>
            Select or drag a .pdf document to begin the document upload process.
            You will then be able to edit document information.
          </p>
        {:else}
          <p>
            {files.length} file{files.length == 1 ? '' : 's'} ready to upload
          </p>
        {/if}
        <div class="actions">
          {#if files.length > 0}
            <span class="padright">
              <Button on:click={upload}>Begin upload</Button>
            </span>
          {:else}
            <FilePicker multiselect={true} on:files={handleFiles}>
              <Button>+ Select files</Button>
            </FilePicker>
          {/if}
        </div>
        {#if files.length == 0}
          <div class="dropper">
            <DropZone on:files={handleFiles}>
              <span>Drag and drop files here</span>
            </DropZone>
          </div>
        {/if}
      </div>
    {/if}
    {#if uploadMode}
      <div>
        {#if !error}
          <h1>Uploading... ({numUploaded}/{files.length})</h1>
          <p>
            Please leave this page open while your documents upload. This dialog
            will automatically close when they have finished uploading.
          </p>
        {:else}
          <h1>Error occurred while uploading</h1>
          <p class="error">
            We failed to {errorMessage}. Please try again later.
          </p>
          <div>
            <Button secondary={true} on:click={emit.allUploaded}>
              Dismiss
            </Button>
          </div>
        {/if}
      </div>
    {/if}
    {#if !uploadMode && files.length > 0}
      <div>
        <p class="subtitle">Edit document information:</p>
      </div>
    {/if}
    {#if files.length > 0}
      <div class="files" class:padder={uploadMode}>
        {#each displayFiles as file (file.index)}
          <File
            class="file"
            file={file.file}
            data={file}
            {uploadMode}
            {error}
            on:name={({ detail: newName }) => {
              file.name = newName;
            }}
            on:delete={() => removeFile(file.index)} />
        {/each}
      </div>
    {/if}
    {#if !uploadMode}
      <div>
        {#if files.length > 0 && !uploadAdditional}
          <div class="vpadded">
            <Button
              nondescript={true}
              on:click={() => (uploadAdditional = true)}>
              Upload additional files
            </Button>
          </div>
        {/if}
        {#if files.length > 0 && uploadAdditional}
          <div>
            <div class="sectionbreak" />
            <FilePicker multiselect={true} on:files={handleFiles}>
              <Button secondary={true} small={true}>+ Select more files</Button>
            </FilePicker>
            <DropZone class="dropper" secondary={true} on:files={handleFiles}>
              <span>Drag and drop additional files here</span>
            </DropZone>
          </div>
        {/if}
      </div>
    {/if}
  </div>
</div>

// src/main_container/UploadDialog.vue
<template>
  <div>
    <div class="mcontent">
      <div v-if="!uploadMode">
        <h1>Document Upload</h1>
        <p v-if="files.length == 0">
          Select or drag a .pdf document to begin the document upload process.
          You will then be able to edit document information.
        </p>
        <p v-else>
          {{ files.length }} file{{ files.length == 1 ? "" : "s" }} ready to
          upload
        </p>
        <div class="actions">
          <Button @click="upload()" class="padright" v-if="files.length > 0"
            >Begin upload</Button
          >
          <FilePicker
            v-if="files.length == 0"
            :multiselect="true"
            @files="handleFiles($event)"
          >
            <Button>+ Select files</Button>
          </FilePicker>
        </div>
        <DropZone
          class="dropper"
          v-if="files.length == 0"
          @files="handleFiles($event)"
        >
          <span>Drag and drop files here</span>
        </DropZone>
      </div>
      <div v-if="uploadMode">
        <h1 v-if="!error">
          Uploading... ({{ numUploaded }}/{{ files.length }})
        </h1>
        <h1 v-if="error">Error occurred while uploading</h1>
        <p v-if="!error">
          Please leave this page open while your documents upload. This dialog
          will automatically close when they have finished uploading.
        </p>
        <p class="error" v-if="error">
          We failed to {{ errorMessage }}. Please try again later.
        </p>
        <div>
          <Button :secondary="true" @click="$emit('allUploaded')"
            >Dismiss</Button
          >
        </div>
      </div>
      <div v-if="!uploadMode && files.length > 0">
        <p class="subtitle">Edit document information:</p>
      </div>
      <div
        class="files"
        v-if="files.length > 0"
        :class="{ padder: uploadMode }"
      >
        <File
          class="file"
          v-for="file in displayFiles"
          :key="file.index"
          :file="file.file"
          :data="file"
          :uploadMode="uploadMode"
          :error="error"
          @name="file.name = $event"
          @delete="removeFile(file.index)"
        />
      </div>
      <div v-if="!uploadMode">
        <div class="vpadded" v-if="files.length > 0 && !uploadAdditional">
          <Button :nondescript="true" @click="uploadAdditional = true"
            >Upload additional files</Button
          >
        </div>
        <div v-if="files.length > 0 && uploadAdditional">
          <div class="sectionbreak" v-if="files.length > 0"></div>
          <FilePicker
            v-if="files.length > 0"
            :multiselect="true"
            @files="handleFiles($event)"
          >
            <Button :secondary="true" :small="true">+ Select more files</Button>
          </FilePicker>
          <DropZone
            class="dropper"
            :secondary="true"
            v-if="files.length > 0"
            @files="handleFiles($event)"
          >
            <span>Drag and drop additional files here</span>
          </DropZone>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import File from "./File";
import Button from "../common/Button";
import DropZone from "../common/DropZone";
import FilePicker from "../common/FilePicker";

// import { UploadRequest } from "../api";
import Vue from "vue";

export default {
  components: { Button, DropZone, FilePicker, File },
  data() {
    return {
      files: [],
      id: 0,
      uploadMode: false,
      uploadFiles: [],
      uploadAdditional: false,
      errorMessage: null
    };
  },
  props: {
    initialFiles: {
      type: Array,
      default: () => []
    }
  },
  mounted() {
    // Add any initial files to the mix.
    this.handleFiles(this.initialFiles);
  },
  computed: {
    displayFiles() {
      if (this.uploadMode == false) return this.files;
      return this.uploadFiles;
    },
    numUploaded() {
      if (!this.uploadMode) return 0;
      let total = 0;
      for (let i = 0; i < this.uploadFiles.length; i++) {
        total += this.uploadFiles[i].done ? 1 : 0;
      }
      return total;
    },
    error() {
      return this.errorMessage != null;
    }
  },
  methods: {
    handleFiles(files) {
      for (let i = 0; i < files.length; i++) {
        this.files.push({
          index: this.id++,
          file: files[i]
        });
      }
    },
    removeFile(index) {
      this.files = this.files.filter(file => file.index != index);
    },
    upload() {
      const uploadFiles = [];
      for (let i = 0; i < this.files.length; i++) {
        uploadFiles.push({
          file: this.files[i].file,
          progress: 0,
          done: false,
          index: i
        });
      }
      this.uploadFiles = uploadFiles;
      this.$emit("setDismissable", false);
      this.uploadMode = true;

      Vue.API.uploadDocuments(
        null,
        this.files,
        (index, progress) => {
          // Progress handler
          this.uploadFiles[index].progress = progress;
        },
        (id, index) => {
          // Complete handler
          this.uploadFiles[index].done = true;
          this.$emit("docUploaded", id);
        },
        () => {
          // All complete handler
          this.$emit("allUploaded");
        },
        message => {
          this.errorMessage = message;
          this.$emit("setDismissable", true);
        }
      );
    }
  }
};
</script>

<style lang="scss" scoped>
.actions {
  margin: 1.5em 0;
}

.hdrawer,
.drawer {
  position: sticky;
  position: -webkit-sticky;
  background: $modal;
}

.hdrawer {
  top: 0;
  padding: $modal-vert-padding 0 16px 0;
  margin-top: -42px;
}

.drawer {
  bottom: 0;
  padding-top: 16px;
  padding-bottom: $modal-vert-padding;
}

.files {
  display: table;
  width: 100%;
}

.padright {
  margin-right: 12px;
}

.dropper {
  margin: 24px 0;
}

.sectionbreak {
  border-bottom: solid 1px $gray;
  margin: 2em 0 1.5em 0;
}

.padder {
  margin: 1.5em 0 2.5em 0;
}

.vpadded {
  margin: 2em 0 2.5em 0;
}

p.subtitle {
  color: $gray;
}
</style>
