// src/pages/app/upload/UploadDialog.svelte
<script>
  import { _ } from "svelte-i18n";
  import { onMount } from "svelte";

  // Components
  import File from "../File.svelte";
  import Button from "@/common/Button.svelte";
  import DropZone from "@/common/DropZone.svelte";
  import FilePicker from "@/common/FilePicker.svelte";
  import UploadOptions from "@/common/UploadOptions.svelte";
  import AccessToggle from "@/common/AccessToggle.svelte";

  // API
  import { defaultLanguage } from "@/api/languages.js";
  import { uploadDocuments } from "@/api/document.js";
  import { search } from "@/search/search.js";
  import { projects } from "@/manager/projects.js";

  // Stores
  import { layout } from "@/manager/layout.js";
  import { handleNewDocuments } from "@/manager/documents.js";

  import emitter from "@/emit.js";

  import {
    UPLOAD_LIMIT,
    PDF_SIZE_LIMIT,
    PDF_SIZE_LIMIT_READABLE,
    DOCUMENT_SIZE_LIMIT,
    DOCUMENT_SIZE_LIMIT_READABLE,
  } from "../../../config/config.js";

  const emit = emitter({
    setDismissable() {},
  });

  export let initialFiles = [];

  $: uploadProject =
    $search.params.oneProjectSearch &&
    $projects.projectsById[$search.params.oneProjectSearch] != null
      ? $projects.projectsById[$search.params.oneProjectSearch]
      : null;

  let files = [];
  let id = 0;
  let uploadMode = false;
  let uploadFiles = [];
  let uploadAdditional = false;
  let errorMessage = null;

  let access = "private";
  let language = defaultLanguage;
  let forceOcr = false;
  let ocrEngine = "tess4";
  let revisionControl = false;

  let tooManyFiles = false;
  let tooManyBigFiles = [false, false];

  $: displayFiles = uploadMode ? uploadFiles : files;

  let numUploaded;
  let createProgress = 0;
  let processProgress = 0;
  let uploadInProgress = false;
  $: {
    // Set numUploaded
    if (!uploadMode) {
      numUploaded = 0;
    } else {
      let total = 0;
      for (let i = 0; i < uploadFiles.length; i++) {
        total += uploadFiles[i].done ? 1 : 0;
      }
      numUploaded = total;
    }
  }
  $: createProgressPercent = `${Math.floor(createProgress * 100)}%`;
  $: processProgressPercent = `${Math.floor(processProgress * 100)}%`;

  $: error = errorMessage !== null;

  onMount(() => {
    handleFiles({ detail: initialFiles });
  });

  function handleFiles({ detail: newFiles }) {
    let hasTooBigPdf = false;
    let hasTooBigDocument = false;

    for (let i = 0; i < newFiles.length; i++) {
      if (files.length < UPLOAD_LIMIT) {
        const newFile = newFiles[i];
        const isPdf = newFile.name.toLowerCase().trim().endsWith(".pdf");
        if (
          (isPdf && newFile.size <= PDF_SIZE_LIMIT) ||
          newFile.size <= DOCUMENT_SIZE_LIMIT
        ) {
          files.push({
            index: id++,
            file: newFile,
          });
        } else {
          if (isPdf) {
            hasTooBigPdf = true;
          } else {
            hasTooBigDocument = true;
          }
        }
        tooManyFiles = false;
      } else {
        tooManyFiles = true;
      }
    }
    tooManyBigFiles = [hasTooBigPdf, hasTooBigDocument];
    files = files;
  }

  function removeFile(index) {
    files = files.filter((file) => file.index != index);
    tooManyBigFiles = false;
    tooManyFiles = false;
  }

  function upload() {
    uploadFiles = files.map((file, i) => {
      return {
        file: file.file,
        progress: 0,
        done: false,
        index: i,
      };
    });
    emit.setDismissable(false);
    uploadMode = true;

    uploadDocuments(
      files,
      access,
      language,
      forceOcr,
      ocrEngine,
      revisionControl,
      uploadProject == null ? [] : [uploadProject],
      (progress) => {
        // Create progress handler
        createProgress = progress;
      },
      (index, progress) => {
        // Progress handler
        uploadInProgress = true;
        uploadFiles[index].progress = progress;
        if (progress >= 1) {
          uploadFiles[index].done = true;
        }
      },
      (progress) => {
        // Process progress handler
        processProgress = progress;
      },
      async (goodDocuments) => {
        // All complete handler
        uploadFiles = uploadFiles.map((file) => ({ ...file, done: true }));
        layout.uploading = false;
        await handleNewDocuments(goodDocuments);
      },
      (message) => {
        layout.error = message;
        layout.uploading = false;
        emit.setDismissable(true);
      },
    );
  }
</script>

<div class="mcontent">
  {#if !uploadMode}
    <div>
      <h2>
        {#if uploadProject == null}
          {$_("uploadDialog.docUpload")}
        {:else}
          {$_("uploadDialog.docUploadProj", {
            values: { title: uploadProject.title },
          })}
        {/if}
      </h2>
      {#if files.length === 0}
        <p>
          {$_("uploadDialog.selectDocument")}
        </p>
        {#if tooManyBigFiles[0]}
          <p class="danger">
            {$_("uploadDialog.pdfSizeWarning", {
              values: { size: PDF_SIZE_LIMIT_READABLE },
            })}
          </p>
        {/if}
        {#if tooManyBigFiles[1]}
          <p class="danger">
            {$_("uploadDialog.pdfSizeWarning", {
              values: { size: DOCUMENT_SIZE_LIMIT_READABLE },
            })}
          </p>
        {/if}
      {:else}
        <p>{$_("uploadDialog.fileReady", { values: { n: files.length } })}</p>
        {#if tooManyFiles}
          <p class="danger">
            {$_("uploadDialog.fileLimitWarning", {
              values: { limit: UPLOAD_LIMIT },
            })}
          </p>
        {/if}
      {/if}
      <div class="actions">
        <UploadOptions
          bind:language
          bind:forceOcr
          bind:ocrEngine
          bind:revisionControl
        />

        {#if files.length > 0}
          <Button on:click={upload}>{$_("uploadDialog.beginUpload")}</Button>
        {:else}
          <FilePicker multiselect={true} on:files={handleFiles}>
            <Button>{$_("uploadDialog.selectFiles")}</Button>
          </FilePicker>
        {/if}
      </div>
      {#if files.length == 0}
        <div class="droparea">
          <DropZone on:files={handleFiles}>
            <span>{$_("uploadDialog.dragDrop")}</span>
          </DropZone>
        </div>
      {/if}
      <div class="bottompadded">
        <AccessToggle
          bind:access
          publicMessage={$_("uploadDialog.publicMsg")}
          collaboratorMessage={$_("uploadDialog.collabMsg")}
          privateMessage={$_("uploadDialog.privateMsg")}
          collaboratorName={$_("uploadDialog.collabName")}
        />
      </div>
    </div>
  {/if}
  {#if uploadMode}
    <div>
      {#if !error}
        <h2>
          {#if numUploaded == files.length}
            {$_("uploadDialog.submitting", {
              values: { percent: processProgressPercent },
            })}
          {:else if uploadInProgress}
            {$_("uploadDialog.uploading", {
              values: { uploaded: numUploaded, length: files.length },
            })}
          {:else}
            {$_("uploadDialog.gettingInfo", {
              values: { percent: createProgressPercent },
            })}
          {/if}
        </h2>
        <p>
          {$_("uploadDialog.pleaseLeaveOpen")}
        </p>
      {:else}
        <h2>{$_("uploadDialog.errorHeading")}</h2>
        <p class="error">
          {$_("uploadDialog.errorMsg", {
            values: { errorMessage: errorMessage },
          })}
        </p>
        <div>
          <Button secondary={true} on:click={emit.allUploaded}>
            {$_("dialog.dismiss")}
          </Button>
        </div>
      {/if}
    </div>
  {/if}
  {#if !uploadMode && files.length > 0}
    <div>
      <p class="subtitle">{$_("uploadDialog.editDocInfo")}</p>
    </div>
  {/if}
  {#if files.length > 0}
    <div class="files" class:padder={uploadMode}>
      {#each displayFiles as file (file.index)}
        <File
          class="file"
          file={file.file}
          data={file}
          {uploadMode}
          {error}
          on:name={({ detail: newName }) => {
            let name = newName.trim();
            if (name.length == 0) name = $_("uploadDialog.untitled");
            file.name = name;
          }}
          on:delete={() => removeFile(file.index)}
        />
      {/each}
    </div>
  {/if}
  {#if !uploadMode}
    <div>
      {#if files.length > 0 && !uploadAdditional}
        <div class="vpadded">
          <Button nondescript={true} on:click={() => (uploadAdditional = true)}
            >{$_("uploadDialog.uploadFiles")}</Button
          >
        </div>
      {/if}
      {#if files.length > 0 && uploadAdditional}
        <div>
          <div class="sectionbreak" />
          <FilePicker multiselect={true} on:files={handleFiles}>
            <Button secondary={true} small={true}>
              {$_("uploadDialog.selectMore")}
            </Button>
          </FilePicker>
          <DropZone class="dropper" secondary={true} on:files={handleFiles}>
            <span>{$_("uploadDialog.dragDropMore")}</span>
          </DropZone>
        </div>
      {/if}
    </div>
  {/if}
</div>

<style lang="scss">
  .actions {
    margin: 1.5em 0;
  }

  .files {
    display: table;
    width: 100%;
  }

  .droparea {
    margin: 24px 0;
  }

  .sectionbreak {
    border-bottom: solid 1px $gray;
    margin: 2em 0 1.5em 0;
  }

  .padder {
    margin: 1.5em 0 2.5em 0;
  }

  .vpadded {
    margin: 2em 0 2.5em 0;
  }

  .bottompadded {
    margin-bottom: 25px;
  }

  p {
    &.subtitle {
      color: $gray;
    }

    &.danger {
      color: $caution;
      font-size: 13px;
    }
  }
</style>

// src/main_container/UploadDialog.vue
<template>
  <div>
    <div class="mcontent">
      <div v-if="!uploadMode">
        <h1>Document Upload</h1>
        <p v-if="files.length == 0">
          Select or drag a .pdf document to begin the document upload process.
          You will then be able to edit document information.
        </p>
        <p v-else>
          {{ files.length }} file{{ files.length == 1 ? "" : "s" }} ready to
          upload
        </p>
        <div class="actions">
          <Button @click="upload()" class="padright" v-if="files.length > 0"
            >Begin upload</Button
          >
          <FilePicker
            v-if="files.length == 0"
            :multiselect="true"
            @files="handleFiles($event)"
          >
            <Button>+ Select files</Button>
          </FilePicker>
        </div>
        <DropZone
          class="dropper"
          v-if="files.length == 0"
          @files="handleFiles($event)"
        >
          <span>Drag and drop files here</span>
        </DropZone>
      </div>
      <div v-if="uploadMode">
        <h1 v-if="!error">
          Uploading... ({{ numUploaded }}/{{ files.length }})
        </h1>
        <h1 v-if="error">Error occurred while uploading</h1>
        <p v-if="!error">
          Please leave this page open while your documents upload. This dialog
          will automatically close when they have finished uploading.
        </p>
        <p class="error" v-if="error">
          We failed to {{ errorMessage }}. Please try again later.
        </p>
        <div>
          <Button :secondary="true" @click="$emit('allUploaded')"
            >Dismiss</Button
          >
        </div>
      </div>
      <div v-if="!uploadMode && files.length > 0">
        <p class="subtitle">Edit document information:</p>
      </div>
      <div
        class="files"
        v-if="files.length > 0"
        :class="{ padder: uploadMode }"
      >
        <File
          class="file"
          v-for="file in displayFiles"
          :key="file.index"
          :file="file.file"
          :data="file"
          :uploadMode="uploadMode"
          :error="error"
          @name="file.name = $event"
          @delete="removeFile(file.index)"
        />
      </div>
      <div v-if="!uploadMode">
        <div class="vpadded" v-if="files.length > 0 && !uploadAdditional">
          <Button :nondescript="true" @click="uploadAdditional = true"
            >Upload additional files</Button
          >
        </div>
        <div v-if="files.length > 0 && uploadAdditional">
          <div class="sectionbreak" v-if="files.length > 0"></div>
          <FilePicker
            v-if="files.length > 0"
            :multiselect="true"
            @files="handleFiles($event)"
          >
            <Button :secondary="true" :small="true">+ Select more files</Button>
          </FilePicker>
          <DropZone
            class="dropper"
            :secondary="true"
            v-if="files.length > 0"
            @files="handleFiles($event)"
          >
            <span>Drag and drop additional files here</span>
          </DropZone>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import File from "./File";
import Button from "../common/Button";
import DropZone from "../common/DropZone";
import FilePicker from "../common/FilePicker";

// import { UploadRequest } from "../api";
import Vue from "vue";

export default {
  components: { Button, DropZone, FilePicker, File },
  data() {
    return {
      files: [],
      id: 0,
      uploadMode: false,
      uploadFiles: [],
      uploadAdditional: false,
      errorMessage: null
    };
  },
  props: {
    initialFiles: {
      type: Array,
      default: () => []
    }
  },
  mounted() {
    // Add any initial files to the mix.
    this.handleFiles(this.initialFiles);
  },
  computed: {
    displayFiles() {
      if (this.uploadMode == false) return this.files;
      return this.uploadFiles;
    },
    numUploaded() {
      if (!this.uploadMode) return 0;
      let total = 0;
      for (let i = 0; i < this.uploadFiles.length; i++) {
        total += this.uploadFiles[i].done ? 1 : 0;
      }
      return total;
    },
    error() {
      return this.errorMessage != null;
    }
  },
  methods: {
    handleFiles(files) {
      for (let i = 0; i < files.length; i++) {
        this.files.push({
          index: this.id++,
          file: files[i]
        });
      }
    },
    removeFile(index) {
      this.files = this.files.filter(file => file.index != index);
    },
    upload() {
      const uploadFiles = [];
      for (let i = 0; i < this.files.length; i++) {
        uploadFiles.push({
          file: this.files[i].file,
          progress: 0,
          done: false,
          index: i
        });
      }
      this.uploadFiles = uploadFiles;
      this.$emit("setDismissable", false);
      this.uploadMode = true;

      Vue.API.uploadDocuments(
        null,
        this.files,
        (index, progress) => {
          // Progress handler
          this.uploadFiles[index].progress = progress;
        },
        (id, index) => {
          // Complete handler
          this.uploadFiles[index].done = true;
          this.$emit("docUploaded", id);
        },
        () => {
          // All complete handler
          this.$emit("allUploaded");
        },
        message => {
          this.errorMessage = message;
          this.$emit("setDismissable", true);
        }
      );
    }
  }
};
</script>

<style lang="scss" scoped>
.actions {
  margin: 1.5em 0;
}

.hdrawer,
.drawer {
  position: sticky;
  position: -webkit-sticky;
  background: $modal;
}

.hdrawer {
  top: 0;
  padding: $modal-vert-padding 0 16px 0;
  margin-top: -42px;
}

.drawer {
  bottom: 0;
  padding-top: 16px;
  padding-bottom: $modal-vert-padding;
}

.files {
  display: table;
  width: 100%;
}

.padright {
  margin-right: 12px;
}

.dropper {
  margin: 24px 0;
}

.sectionbreak {
  border-bottom: solid 1px $gray;
  margin: 2em 0 1.5em 0;
}

.padder {
  margin: 1.5em 0 2.5em 0;
}

.vpadded {
  margin: 2em 0 2.5em 0;
}

p.subtitle {
  color: $gray;
}
</style>
