// src/common/Draggable.svelte
<script>
  import emitter from "@/emit.js";
  import { filterFiles } from "./fileHandler.js";

  const emit = emitter({
    files() {},
  });

  let dragging = false;
  export let disabled = false;

  function enter(e) {
    if (disabled) return;
    dragging = true;
  }

  function leave() {
    if (disabled) return;
    dragging = false;
  }

  function handleDrop(e) {
    if (disabled) return;
    handleFiles(e.dataTransfer.files);
  }

  function handleFiles(files) {
    if (disabled) return;
    leave();
    files = filterFiles(Array.from(files));
    if (files.length == 0) return;
    emit.files(files);
  }
</script>

<style lang="scss">
  .outer {
    display: table;
    width: 100%;
    height: 100%;
    position: relative;
  }
  .outer :global(.upload) {
    height: 150px;
    width: 100%;
    display: table-cell;
    vertical-align: middle;
    padding: 20px;
    box-sizing: border-box;
    text-align: center;
    font-weight: bold;
    background: #fffafb;
    color: black;
    transition: all 0.2s ease;
    border-radius: 6px;
  }

  .outer :global(input[type="file"]) {
    position: absolute;
    left: 0;
    width: 100%;
    top: 0;
    bottom: 0;
    opacity: 0;
    cursor: pointer;
  }
  .outer :global(input[type="file"]):hover + :global(.upload),
  .outer :global(input[type="file"].dragging) + :global(.upload) {
    background: #fc4762;
    color: white;
  }
</style>

<div
  class="outer"
  class:dragging
  on:dragenter|preventDefault={enter}
  on:dragover|preventDefault={enter}
  on:dragleave|preventDefault={leave}
  on:drop|preventDefault={handleDrop}
>
  <slot />
</div>

// common/Draggable.vue
<template>
  <div
    class="outer"
    :class="{dragging}"
    @dragenter="enter($event)"
    @dragover="enter($event)"
    @dragleave="leave()"
    @drop="handleDrop($event)"
  >
    <slot></slot>
  </div>
</template>

<script>
export default {
  data() {
    return {
      dragging: false
    };
  },
  methods: {
    enter(e) {
      e.preventDefault();
      this.dragging = true;
    },
    leave() {
      this.dragging = false;
    },
    handleDrop(e) {
      e.preventDefault();
      this.handleFiles(e.dataTransfer.files);
    },
    handleFiles(files) {
      this.leave();
      if (files.length == 0) return;
      window.console.log(files);
      this.$emit("upload", files);
    }
  }
};
</script>

<style scoped>
.upload {
  height: 150px;
  width: 100%;
  display: table-cell;
  vertical-align: middle;
  padding: 20px;
  box-sizing: border-box;
  text-align: center;
  font-weight: bold;
  background: #fffafb;
  color: black;
  transition: all 0.2s ease;
  border: solid 1px var(--accent);
  border-radius: 6px;
}

input[type="file"]:hover + .upload,
input[type="file"].dragging + .upload {
  background: #fc4762;
  color: white;
}

.outer {
  display: table;
  width: 100%;
  position: relative;
}

input[type="file"] {
  position: absolute;
  left: 0;
  width: 100%;
  top: 0;
  bottom: 0;
  opacity: 0;
  cursor: pointer;
}
</style>
